# Generated by Django 4.2 on 2023-04-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['sent_date'], 'verbose_name': 'Назначение записей', 'verbose_name_plural': 'Назначение записей'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Подтверждение'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sent_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата записи'),
        ),
    ]
