# Generated by Django 4.2 on 2023-04-17 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0002_alter_appointment_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appoint.specialist'),
        ),
    ]
