# Generated by Django 4.2 on 2023-04-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0002_alter_appointment_options_alter_appointment_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='accepted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Назначеное время'),
        ),
    ]
