# Generated by Django 4.2 on 2023-04-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0003_specialist_appointment_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appoint.specialist', verbose_name='Специалист'),
        ),
    ]
