# Generated by Django 4.2 on 2023-04-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0004_alter_appointment_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request',
            field=models.TextField(blank=True, verbose_name='Обращение'),
        ),
    ]
