# Generated by Django 4.2 on 2023-04-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0006_appointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
    ]
